config/routes.rb
Rails.application.routes.draw do
  
  get 'introductions/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  root "users#show"
  
  resources :users, only: :show do
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :introductions, only: [:index, :new, :create, :edit, :update]
  end
  
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_user

  def index
    @note = Note.new
    @notes = @user.notes.order(id: "DESC")
  end

  def new
    @note = Note.new
  end

  def create
    @note = @user.notes.new(note_params)
    if @note.save
      redirect_to user_notes_path(@user), notice: "ノートが投稿できました"
    else
      @notes = @user.notes
      flash.now[:alert] = "ノートを入力してください"
      render :new
    end
  end

  def edit
    @note = @user.notes.find(params[:id])
  end

  def update
    @note = @user.notes.find(params[:id])
    if @note.update(note_params)
      redirect_to user_notes_path(current_user.id), notice: "ノートを更新しました"
    else
      render :edit
    end
  end

  def destroy
    @note = @user.notes.find(params[:id])
    @note.destroy
    redirect_to user_notes_path, notice: "ノートを削除しました"
  end

  private

  def note_params
    params.require(:note).permit(:date, :title, :quotation, :effort, :achievement, :todo, :free, :memo)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.haml
.Note-box
  .Note-box__left
    日付:
    = note.date
    %br
    タイトル:
    = note.title
  .Note-box__right
    = icon("fas", "caret-down", class: "Note-box-icon")
.Note-box__bottom
  .Note-box-item
    良い言葉:
    %span.Note-box-content
      = note.quotation
  .Note-box-item
    頑張ったこと:
    %span.Note-box-content
      = note.effort
  .Note-box-item
    できるようになったこと:
    %span.Note-box-content
      = note.achievement
  .Note-box-item
    明日やること:
    %span.Note-box-content
      = note.todo
  .Note-box-item
    自由欄:
    %span.Note-box-content
      = note.free
  .Note-box-item
    メモ:
    %span.Note-box-content
      = note.memo
  .Note-box-btns
    = link_to "削除", user_note_path(current_user.id, note.id), method: :delete, class: "NoteForm-btn" 
    = link_to "編集", edit_user_note_path(current_user.id, note.id), class: "NoteForm-btn"

app/views/notes/edit.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    = form_with model: [@user, @note], html: {class: "NoteForm"}, local: true do |f|
      %h3.NoteForm-title 日記の入力欄
      .NoteForm__top
        = f.label :date, "日付"
        = f.text_field :date, class: "NoteForm--small"
        = f.label :title, "タイトル"
        = f.text_field :title, class: "NoteForm--small"
        = f.label :quotation, "良い言葉"
        = f.text_field :quotation, class: "NoteForm--small"
        = f.label :effort, "頑張ったこと"
        = f.text_field :effort, class: "NoteForm--small"
        = f.label :achievement, "できるようになったこと"
        = f.text_field :achievement, class: "NoteForm--small"
        = f.label :todo, "明日やること"
        = f.text_field :todo, class: "NoteForm--small"
        = f.label :free, "自由欄"
        = f.text_field :free, class: "NoteForm--small"
        = f.label :memo, "メモ"
        = f.text_area :memo, class: "NoteForm--large"
      .NoteForm__bottom
        = link_to "戻る", user_notes_path, class: "NoteForm-btn" 
        = f.submit "更新", class: "NoteForm-btn"

app/views/notes/index.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    .Note
      .Note__top
        = link_to new_user_note_path, class: "Note-btn" do
          = icon('fas', 'pen', class: 'Note-btn-icon')
          枠内をクリックしてノートを入力
      .Note__bottom
        = render @notes

app/views/notes/new.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    = form_with model: [@user, @note], html: {class: "NoteForm"}, local: true do |f|
      %h3.NoteForm-title 日記の入力欄
      .NoteForm__top
        = f.label :date, "日付"
        = f.text_field :date, class: "NoteForm--small"
        = f.label :title, "タイトル"
        = f.text_field :title, class: "NoteForm--small"
        = f.label :quotation, "良い言葉"
        = f.text_field :quotation, class: "NoteForm--small"
        = f.label :effort, "頑張ったこと"
        = f.text_field :effort, class: "NoteForm--small"
        = f.label :achievement, "できるようになったこと"
        = f.text_field :achievement, class: "NoteForm--small"
        = f.label :todo, "明日やること"
        = f.text_field :todo, class: "NoteForm--small"
        = f.label :free, "自由欄"
        = f.text_field :free, class: "NoteForm--small"
        = f.label :memo, "メモ"
        = f.text_area :memo, class: "NoteForm--large"
      .NoteForm__bottom
        = link_to "戻る", user_notes_path, class: "NoteForm-btn" 
        = f.submit "保存", class: "NoteForm-btn"