config/routes.rb
Rails.application.routes.draw do
  
  get 'introductions/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  root "users#show"
  
  resources :users, only: :show do
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :introductions, only: [:index, :new, :create, :edit, :update]
  end
  
end

app/models/introduction.rb
class Introduction < ApplicationRecord
  belongs_to :user
end

app/controllers/introductions_controller.rb
class IntroductionsController < ApplicationController
  before_action :set_user

  def index
    @introductions1 = Introduction.where(user_id: current_user.id).first(3)
    @introductions2 = Introduction.where(user_id: current_user.id).limit(2).offset(3)
    @introductions3 = Introduction.where(user_id: current_user.id).limit(2).offset(5)
  end

  def new
    @introduction = Introduction.new
  end

  def create
    @introduction = @user.introductions.new(introduction_params)
    if @introduction.save
      redirect_to user_introductions_path(@user), notice: "自己紹介文が作成できました"
    else
      @introductions = @user.introductions
      flash.now[:alert] = "自己紹介文を入力してください"
      render :new
    end
  end

  def edit
    @introduction = @user.introductions.find(params[:id])
  end

  def update
    @introduction = @user.introductions.find(params[:id])
    if @introduction.update(introduction_params)
      redirect_to user_introductions_path(current_user.id), notice: "自己紹介文を更新しました"
    else
      render :edit
    end
  end

  private

  def introduction_params
    params.require(:introduction).permit(:title, :content)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
  
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/views/introductions/edit.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    = form_with model: [@user, @introduction], class: "IntroductionForm", data: { remote: false} do |f|
      %h2.IntroductionForm__top 自己紹介文編集
      .IntroductionForm__middle
        = f.label :title, "タイトル", class: "IntroductionForm-label"
        = f.text_field :title, class: "IntroductionForm-input"
        = f.label :content, "自己紹介文", class: "IntroductionForm-label"
        = f.text_area :content, class: "IntroductionForm-textarea"
      .IntroductionForm__bottom
        = link_to "戻る", "#", class: "IntroductionForm-btn"
        = f.submit "保存", class: "IntroductionForm-btn"

app/views/introductions/index.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    アプリの仕様上、上から順に完成させてください！
    .Introductions
      .Introductions__top
        .Introductions__left
          .Introductions-time 30秒用
          %span.Introductions-text (文字数150〜200字)
        .Introductions__right
          - @introductions1.each do |introduction|
            - if introduction.id.present?
              = link_to edit_user_introduction_path(current_user.id, introduction.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
                  = introduction.title
          - if @introductions1.length == 0
            - 3.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
          - if @introductions1.length == 1
            - 2.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
          - if @introductions1.length == 2
            - 1.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
      .Introductions__bottom
        .Introductions__left
          .Introductions-time 1分用
          %span.Introductions-text (文字数300〜400字)
        .Introductions__right
          - @introductions2.each do |introduction|
            - if introduction.id.present?
              = link_to edit_user_introduction_path(current_user.id, introduction.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
                  = introduction.title
          - if @introductions2.length == 0
            - 2.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
          - if @introductions2.length == 1
            - 1.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
      .Introductions__bottom
        .Introductions__left
          .Introductions-time 自由欄
          %span.Introductions-text 好きなように書こう！
        .Introductions__right
          - @introductions3.each do |introduction|
            - if introduction.id.present?
              = link_to edit_user_introduction_path(current_user.id, introduction.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
                  = introduction.title
          - if @introductions3.length == 0
            - 2.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:
          - if @introductions3.length == 1
            - 1.times do 
              = link_to new_user_introduction_path(current_user.id), class: "Introductions-link" do
                .Introductions-item
                  タイトル:

app/views/introductions/new.html.haml
= render partial: 'layouts/header'
.container
  = render partial: 'layouts/sidebar'
  .Main
    = form_with model: [@user, @introduction], html: {class: "IntroductionForm"}, local: true do |f|
      %h3.IntroductionForm__top 自己紹介文作成
      .IntroductionForm__middle
        = f.label :title, "タイトル", class: "IntroductionForm-label"
        = f.text_field :title, class: "IntroductionForm-input"
        = f.label :content, "自己紹介文", class: "IntroductionForm-label"
        = f.text_area :content, class: "IntroductionForm-textarea"
      .IntroductionForm__bottom
        = link_to "戻る", user_introductions_path, class: "IntroductionForm-btn"
        = f.submit "保存", class: "IntroductionForm-btn"