config/routes.rb
Rails.application.routes.draw do
  
  get 'introductions/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  root "users#show"
  
  resources :users, only: :show do
    resources :notes, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :introductions, only: [:index, :new, :create, :edit, :update]
  end
  
end

app/views/layouts/_header.html.haml
%header.Header
  .Header__left
    .Menu
      = icon('fas', 'bars', class: 'Menu-icon')
    .Title
      .Title__left
        = icon('fas', 'book', class: 'Title-icon')
      .Title__right
        %span.Title-text MYSELF
  .Header__center
    .Search
      %form.Search__form
        .Search__form__left
          = icon('fas', 'search', class: 'Search__form-icon')
        .Search__form__center
          %input.Search__form-text{type: 'search', placeholder: 'ここに入力して検索'}
        .Search__form__right
          = icon('far', 'times-circle', class: 'Search__form-delete')
    .Sub
      .Sub__left
        = icon('fas', 'redo-alt', class: 'Sub-reload')
      .Sub__center
        = icon('fas', 'equals', class: 'Sub-display')
      .Sub__right
        = icon('fas', 'cog', class: 'Sub-option')
  .Header__right
    .User
      .User__left
        = link_to  edit_user_registration_path, class: "User-link" do
          = icon('fas', 'id-card', class: 'User-icon')
      .User__right
        = link_to root_path, class: "User-name" do
          = current_user.username

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/_option.html.haml
.OptionModal
  .OptionModal__background
  .OptionModal__content
    %h2 設定（実装中です）
    .OptionModal__item
      %h3 カラー
      .ColorBox
        %button{type: "button", class: "ColorBox-btn", id: "default-color"} デフォルト
        %button{type: "button", class: "ColorBox-btn", id: "pop-color"} ポップ
        %button{type: "button", class: "ColorBox-btn", id: "cute-color"} キュート
        %button{type: "button", class: "ColorBox-btn", id: "cadual-color"} カジュアル
        %button{type: "button", class: "ColorBox-btn"} インパクト
    .OptionModal__item
      %h3 フォント
    = link_to "閉じる", class: "OptionModal__close"

app/views/layouts/_sidebar.html.haml
%aside.Sidebar
  .Sidebar__top
    = link_to user_notes_path(current_user.id), class: "MenuBox-link" do
      .MenuBox
        .MenuBox-icon
          = icon('fas', 'user-edit')
        %span.MenuBox-text Notes
    = link_to user_introductions_path(current_user.id), class: "MenuBox-link" do
      .MenuBox
        .MenuBox-icon
          = icon('far', 'comment')
        %span.MenuBox-text Introductions
  .Sidebar__bottom
    .Rule
      = link_to "#", class: "Rule__link" do
        プライバシー
      %span ・
      = link_to "#", class: "Rule__link" do
        利用規約
      %br
      = link_to "#", class: "Rule__link" do
        オープンソースライセンス

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MYSELF
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield
    = render 'layouts/option'